#!/bin/bash

##### Aliases for git

alias gits='git status'
alias gitb='git branch'
alias gitc='git commit -a'
alias gitA='git add -A .'
alias master='git checkout master'
alias mpush='git push origin master'
alias mpull='git pull origin master'
alias develop='git checkout develop'
alias devpull='git pull origin develop'
alias devpush='git push origin develop'

# Formatting for git log
alias gitl='git log --graph --pretty=format:'\''%Cred%h%Creset %an: %s - %Creset %C(yellow)%d%Creset %Cgreen(%cr)%Creset'\'' --abbrev-commit --date=relative'

# Command prompt displays current branch
parse_git_branch() {
    git branch 2> /dev/null | sed -e '/^[^*]/d' -e 's/* \(.*\)/ (\1)/'
}
export PS1="\W\[\033[32m\]\$(parse_git_branch)\[\033[00m\]: ";
